services:
  - type: web
    name: fraudvision
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
